version: '3'
services: 
  solr: 
    image: solr:6.6
    ports: 
      - "8983:8983"
    volumes: 
      - type: bind
        source: /opt/docker-solr-start/solr66/data
        target: /var/solr

      - type: bind
        source: /opt/docker-solr-start/solr66/settings/config/conf
        target: /opt/solr/server/solr/configsets/myconfig/conf

      - type: bind
        source: /opt/docker-solr-start/solr66/settings/dic
        target: /opt/solr/server/resources/dic

      - type: bind
        source: /opt/docker-solr-start/solr66/settings/lib
        target: /opt/solr/server/solr-webapp/webapp/WEB-INF/lib
    entrypoint:
      - solr-precreate
      - collection1
      - /opt/solr/server/solr/configsets/myconfig

volumes:
  data:
  config:
  dic:
  lib:
